# copied and elaborated from https://www.pulumi.com/docs/guides/continuous-delivery/google-cloud-build/
#
# BUILD_TYPE can be:
# 1. "PullRequest"   (preview) or
# 2. "Anything else" (apply): see shell script.
# IT WORKS!
#
# ENV vars which are useful to us explained verbosely below.
#
steps:
- name: python
  entrypoint: /bin/sh
  args:
  - '-c'
  # TODO(ricc): adapt this to current example: examples/python-gcp-cloudbuild-auto-trigger/
  # even better, make it parametric.
  - 'cd examples/python-gcp-cloudbuild-auto-trigger/ && chmod +x cloudbuild-v2/*.sh && ./cloudbuild-v2/pulumi-for-python.sh'
  env:
  - 'PULUMI_ACCESS_TOKEN=$_INSECURE_SUBSTITUTION_PULUMI_ACCESS_TOKEN'
  - 'BUILD_TYPE=$_BUILD_TYPE'
  - 'PULUMI_PROJECT=$_PULUMI_PROJECT'
  - 'PULUMI_STACK=$_PULUMI_STACK'
  - 'CODE_SUBFOLDER=$_CODE_SUBFOLDER'
  - 'GCP_REGION=$_GCP_REGION'
  - 'GCP_PROJECT=$_GCP_PROJECT'
