# copied and elaborated from https://www.pulumi.com/docs/guides/continuous-delivery/google-cloud-build/
#
# BUILD_TYPE can be:
# 1. "PullRequest" (preview) or
# 2. anytihng else (apply): see shell script.
# IT WORKS!
steps:
- name: python
  entrypoint: /bin/sh
  args:
  - '-c'
  # TODO(ricc): adapt this
  - 'cd pulumi/2022-09-10-kuberic/ && chmod +x cloudbuild/*.sh && ./cloudbuild/pulumi.sh'
  env:
  - 'PULUMI_ACCESS_TOKEN=$_INSECURE_SUBSTITUTION_PULUMI_ACCESS_TOKEN'
  - 'BUILD_TYPE=$_BUILD_TYPE'
