

install-deps:
	venv/bin/pip install -r requirements.txt

# broken, its an OUTPUT not a config. Silly me
see-on-web:
	echo Open this with browser:
	pulumi config get pulumi-readme-url
	#open `pulumi config get pulumi-readme-url`
